name: Build Docker Images

on:
  pull_request:
    branches: master
  push:
    branches: master
    tags:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: latest
      
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
      
    - name: DockerHub Login
      run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
    
    - name: Pre-check
      id: precheck
      run: |
          BUILD_BASE=$(git diff-tree --no-commit-id --name-only -r "$GITHUB_SHA" | grep "base/Dockerfile" | wc -l)
          echo "::set-output name=BUILD_BASE::${BUILD_BASE}" 
          echo "BUILD_BASE: ${BUILD_BASE}, GITHUB_REF: $GITHUB_REF, GITHUB_SHA: $GITHUB_SHA"

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
      
    - name: Run go mod download
      run: go mod download

    - name: Install
      id: install
      run: |
        make dev-deps

    - name: Build
      id: build
      run: |
        make lint
        make build
        make test
        "./docker-volume-rclone"
        
    - name: Docker Plugin
      id: docker-plugin
      run: |
        make docker-plugin PLUGIN_USER=${{ secrets.DOCKER_USER }}
        make docker-plugin-push PLUGIN_USER=${{ secrets.DOCKER_USER }}
